ranker_hidden_dim: 100
two_hop_type_list: /data2/moeller/current_data/decisive_candidates_two_hops_aida_letitov_new.json
limited: false
_10sec: false
adapter_models: true
add_correct_candidate_during_training: true
alternative_description: null
batch_size: 8
dim: 300
embedding_comparison_weight: 1.0
evaluate_every_n_epoch: 1
gradient_accumulation_size: 1
head_lr: 0.003
hops: 0
include_ookg_score: true
lr: 3.0e-05
mask_ratio: 0.0
max_length: 512
max_length_description_encoder: 32
mention_split: 10
mentions_to_add_if_full: 10
mix_other_mentions: true
num_cluster_candidates: 0
num_epochs: 10
num_mentions_in_cluster: 1
num_weak_negatives: 10
num_weak_negatives_mentions: 50
number_candidates: 20
number_candidates_eval: 100
ookg_probability: 0.5
separate_mention_training: true
store_every_n_epoch: 50
transformer_dropout: 0.1
type_embedding_comparison_weight: 0.0
use_context_embeddings: true
use_contextual_types: false
use_cosine: true
use_edit_distance_in_comparator: true
use_popularity: true
use_sample_weight: false
use_transe: true
use_transe_embeddings_in_comparator: true
use_types: false
im_kg_path: /data1/moeller/wikinews_extended/parsed_dump_2019_onetwohop_wikinews_2019_enriched.jsonl
training_dataset_path: datasets/wikievents/wikievents_2000-2022_train.json
dev_dataset_path: datasets/wikievents/wikievents_2000-2022_dev.json
test_dataset_path: datasets/wikievents/wikievents_2000-2022_test.json
mention_dictionary_file: /data1/moeller/wikinews_extended/wikievents_2000-2022_revised_v2_mention_dictionary.json
type_list: /data2/moeller/current_data/decisive_candidates_71_wikievents_2019.json
transe_embeddings_file: /data1/moeller/transe/wikidata_translation_v1_vectors_filtered_revised.npy
transe_mappings_file: /data1/moeller/transe/wikidata_translation_mapping_revised.json

